basic.showNumber(100)
basic.showIcon(IconNames.Heart)
basic.showArrow(ArrowNames.West)
basic.pause(100)
basic.showString("Bonjour, je m'appelle Gabriel ")
basic.pause(100)
basic.showArrow(ArrowNames.East)
basic.pause(100)
basic.showIcon(IconNames.Heart)
basic.showNumber(200)